from enum import Enum


class Classes(Enum):

    # Title
    TITLE_IC = 1
    TITLE_MANAGER = 2
    TITLE_EXECUTIVE = 3

    # Company Category
    COMPANY_RPA = 4
    COMPANY_CUSTOMER = 5
    COMPANY_CONSULTANCY = 6

    # Department
    DEPARTMENT_SALES = 7
    DEPARTMENT_FINANCE = 8
    DEPARTMENT_HR = 9
    DEPARTMENT_IT = 10
    DEPARTMENT_MARKETING = 11
    DEPARTMENT_ENGINEERING = 12
    DEPARTMENT_DATA_SCIENCE = 13
    DEPARTMENT_LEGAL = 14
    DEPARTMENT_MEDICAL = 15
    DEPARTMENT_OPERATIONS = 16
    DEPARTMENT_C_SUITE = 17
    DEPARTMENT_RPA_COE = 18
    DEPARTMENT_CUSTOMER_SUCCESS = 19
    DEPARTMENT_RPA_DEVELOPMENT = 20
    
    # Industry
    INDUSTRY_AGRICULTURE = 21
    INDUSTRY_BUSINESS_SERVICES = 22
    INDUSTRY_CONSTRUCTION = 23
    INDUSTRY_CONSUMER_SERVICES = 24
    INDUSTRY_EDUCATION = 25
    INDUSTRY_ENERGY_UTILITIES_WASTE = 26
    INDUSTRY_FINANCE = 27
    INDUSTRY_GOVERNMENT = 28
    INDUSTRY_HEALTHCARE_SERVICES = 29
    INDUSTRY_HOLDING_COMPANIES_CONGLOMERATES = 30
    INDUSTRY_HOSPITALITY = 31
    INDUSTRY_HOSPITALS_PHYSICIANS_CLINICS = 32
    INDUSTRY_INSURANCE = 33
    INDUSTRY_LAW_FIRMS_LEGAL_SERVICES = 34
    INDUSTRY_MANUFACTURING = 35
    INDUSTRY_MEDIA_INTERNET = 36
    INDUSTRY_MINERALS_MINING = 37
    INDUSTRY_ORGANIZATIONS = 38
    INDUSTRY_REAL_ESTATE = 39
    INDUSTRY_RETAIL = 40
    INDUSTRY_SOFTWARE = 41
    INDUSTRY_TELECOMMUNICATIONS = 42
    INDUSTRY_TRANSPORTATION = 43
    INDUSTRY_RPA_SOFTWARE = 44
