from enum import Enum


class Classes(Enum):

    # Title
    TITLE_IC_MANAGER = 1
    TITLE_IC_EXECUTIVE = 2

    # Company Category
    COMPANY_RPA = 1
    COMPANY_CUSTOMER = 2
    COMPANY_CONSULTANCY = 3

    # Department
    DEPARTMENT_SALES = 1
    DEPARTMENT_FINANCE = 2
    DEPARTMENT_HR = 3
    DEPARTMENT_IT = 4
    DEPARTMENT_MARKETING = 5
    DEPARTMENT_ENGINEERING = 6
    DEPARTMENT_DATA_SCIENCE = 7
    DEPARTMENT_LEGAL = 8
    DEPARTMENT_MEDICAL = 9
    DEPARTMENT_OPERATIONS = 10
    DEPARTMENT_C_SUITE = 11
    DEPARTMENT_RPA_COE = 12
    DEPARTMENT_CUSTOMER_SUCCESS = 13

    # Industry
    INDUSTRY_AGRICULTURE = 1
    INDUSTRY_BUSINESS_SERVICES = 2
    INDUSTRY_CONSTRUCTION = 3
    INDUSTRY_CONSUMER_SERVICES = 4
    INDUSTRY_EDUCATION = 5
    INDUSTRY_ENERGY_UTILITIES_WASTE = 6
    INDUSTRY_FINANCE = 7
    INDUSTRY_GOVERNMENT = 8
    INDUSTRY_HEALTHCARE_SERVICES = 9
    INDUSTRY_HOLDING_COMPANIES_CONGLOMERATES = 10
    INDUSTRY_HOSPITALITY = 11
    INDUSTRY_HOSPITALS_PHYSICIANS_CLINICS = 12
    INDUSTRY_INSURANCE = 13
    INDUSTRY_LAW_FIRMS_LEGAL_SERVICES = 14
    INDUSTRY_MANUFACTURING = 15
    INDUSTRY_MEDIA_INTERNET = 16
    INDUSTRY_MINERALS_MINING = 17
    INDUSTRY_ORGANIZATIONS = 18
    INDUSTRY_REAL_ESTATE = 19
    INDUSTRY_RETAIL = 20
    INDUSTRY_SOFTWARE = 21
    INDUSTRY_TELECOMMUNICATIONS = 22
    INDUSTRY_TRANSPORTATION = 23
    INDUSTRY_RPA_SOFTWARE = 24
