import shutil
import site
import tempfile
from pathlib import Path
from textwrap import dedent

import click
from git import Repo


@click.group()
def summ():
    pass


@summ.command()
@click.option("--template", "-t", default="otter", type=click.Choice(["otter"]))
@click.argument(
    "destination",
    type=click.Path(
        exists=False,
        writable=True,
        path_type=Path,
        dir_okay=False,
        file_okay=False,
        resolve_path=True,
    ),
)
def init(template: str, destination: Path):
    with tempfile.TemporaryDirectory() as tempdir:
        Repo.clone_from("https://github.com/yasyf/summ.git", tempdir)
        shutil.copytree(Path(tempdir) / "summ" / "examples" / template, destination)

    (destination / "__init__.py").unlink()

    impl_init = destination / "implementation" / "__init__.py"
    impl_init.write_text(
        dedent(
            f"""
    # generated by summ init {template}
    import site; site.addsitedir("{site.getsitepackages()[0]}")
    """
        )
        + "\n"
        + impl_init.read_text()
    )

    click.echo(f"Created example project in {destination}")
